### PR TITLE
Handle NativeModules being null

### LINKED ISSUE #223: Error: Cannot create URL for blob
The issue apparently lies in [`NativeModules`](https://github.com/charpeni/react-native-url-polyfill/blob/c32cbdc97fb6569edd6d941c3600196debeb0ad5/js/URL.js#L5). The import is `undefined` and, thus, `BLOB_URL_PREFIX` remains `null`. This [patch](https://github.com/acostalima/react-native-polyfill-globals/blob/master/patches/react-native-url-polyfill%2B1.2.0.patch) fixes the problem. 

Has anyone else experienced this as well? It's happening on RN v0.63.2 on my end.
@charpeni, let know if you want me to open a PR to address this.

Related: https://github.com/ipfs/js-ipfs/issues/2813

### PR DESCRIPTION
**Pull request by kennym**
This fixes #223

### CODE REVIEW

**Comment by charpeni** [comment]
Hmm, it looks like this is not backward compatible with React Native 0.60: https://app.circleci.com/pipelines/github/charpeni/react-native-url-polyfill/989/workflows/357e498d-62eb-42ef-8f2c-499614b0d937/jobs/4759.

**Comment by kennym** [comment]
@charpeni I tried wrapping the `require` statement in try-catch block, but it's still failing - any ideas?

**Comment by kennym** [comment]
@charpeni I tried a few different things, but none seem to work for 0.60 - I have a hunch that if you looked at the code you might know how to fix this! Can you please help me with this one?

**Comment by charpeni** [comment]
@kennym Of course! I'll take time to look at this during the week. Thanks for documenting what you tried in this PR.

**Comment by kennym** [comment]
Closing because this is being addressed with #267 ! Thanks @charpeni

**Pull request closed without merging**
